// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

/**
 * Central registry of native gameplay tags for the bending system.
 * These are available in C++ and automatically show up in the editor tag picker.
 */
namespace ATLATags
{
	// Elements
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Water);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Earth);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Fire);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Air);

	// Water abilities (first element we build)
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Water_Pull);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Water_Whip);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Water_Shield);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Water_IceSpears);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Water_IceWall);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Water_Octopus);

	// Movement techniques
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Movement_Dodge);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Movement_Dodge);

	// Earth abilities
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Earth_Jab);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Earth_Boulder);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Earth_Spikes);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Earth_Wall);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Earth_Armor);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Earth_Launch);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Earth_Root);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Earth_Hoist);

	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Earth_Jab);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Earth_Boulder);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Earth_Spikes);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Earth_Wall);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Earth_Armor);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Earth_Launch);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Earth_Hoist);

	// Fire abilities
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire_Jab);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire_Blast);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire_Arc);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire_Lash);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire_Lightning);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire_Wall);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire_Nova);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire_Jet);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire_Breath);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire_Stream);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Fire_Jab);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Fire_Blast);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Fire_Arc);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Fire_Wall);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Fire_Nova);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Fire_Jet);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Fire_Lightning);

	// Air abilities
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Air_Blast);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Air_Swipe);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Air_Shield);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Air_Cyclone);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Air_Scooter);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Air_Updraft);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Air_Blast);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Air_Swipe);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Air_Shield);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Air_Cyclone);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Air_Scooter);

	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Bending_Empowered);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Fire_Stoked);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Fire_Blazing);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Earth_Grounded);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Earth_Rooted);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Earth_Armored);

	// Cooldowns
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Water_Whip);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Water_IceSpears);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Water_IceWall);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Water_Octopus);

	// Co-op combo system
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combo_Window_Open);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combo_Channeling);

	// Ability lifecycle states
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Bending);
	ATLA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
}
