"""Dump every installed Niagara system/emitter + pack animation into
Design/vfx-inventory.md — the ground truth for the VFX migration."""
import os
import unreal

ar = unreal.AssetRegistryHelpers.get_asset_registry()
OWN = ("/Game/Anims/", "/Game/Bending/", "/Game/ThirdPerson/", "/Game/Characters/",
       "/Game/Input/", "/Game/LevelPrototyping/", "/Game/Variant_")

def scan(cls_path, cls_name):
    out = {}
    for d in ar.get_assets_by_class(unreal.TopLevelAssetPath(cls_path, cls_name), True):
        p = str(d.package_name)
        if p.startswith("/Game/") and not p.startswith(OWN):
            root = p.split("/")[2]
            out.setdefault(root, []).append(p)
    return out

systems = scan("/Script/Niagara", "NiagaraSystem")
emitters = scan("/Script/Niagara", "NiagaraEmitter")
anims = scan("/Script/Engine", "AnimSequence")
montages = scan("/Script/Engine", "AnimMontage")

lines = ["# VFX / animation pack inventory (auto-generated by Tools/inventory_packs.py)", ""]
lines.append("## Niagara systems by pack")
for root in sorted(systems):
    lines.append("\n### %s (%d systems)" % (root, len(systems[root])))
    for p in sorted(systems[root]):
        lines.append("- `%s`" % p)
lines.append("\n## Niagara emitters by pack")
for root in sorted(emitters):
    lines.append("\n### %s (%d emitters)" % (root, len(emitters[root])))
    for p in sorted(emitters[root])[:40]:
        lines.append("- `%s`" % p)
lines.append("\n## Pack animations")
for root in sorted(anims):
    lines.append("\n### %s (%d sequences)" % (root, len(anims[root])))
    for p in sorted(anims[root])[:60]:
        lines.append("- `%s`" % p)
for root in sorted(montages):
    lines.append("\n### %s (%d montages)" % (root, len(montages[root])))

PROJECT_ROOT = unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir())
with open(os.path.join(PROJECT_ROOT, "Design", "vfx-inventory.md"), "w") as f:
    f.write("\n".join(lines) + "\n")

unreal.log("INV systems=%d emitters=%d animroots=%s" % (
    sum(len(v) for v in systems.values()), sum(len(v) for v in emitters.values()),
    {k: len(v) for k, v in anims.items()}))
unreal.log("INV roots: %s" % sorted(set(list(systems) + list(anims))))
unreal.log("INV COMPLETE")
